# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relay_d/acquisition/qt_app/ui/containers/actuactorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 539)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_actuator_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_actuator_name.sizePolicy().hasHeightForWidth())
        self.label_actuator_name.setSizePolicy(sizePolicy)
        self.label_actuator_name.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(63)
        self.label_actuator_name.setFont(font)
        self.label_actuator_name.setScaledContents(False)
        self.label_actuator_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_actuator_name.setWordWrap(False)
        self.label_actuator_name.setObjectName("label_actuator_name")
        self.verticalLayout.addWidget(self.label_actuator_name)
        self.label_actuator_state = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_actuator_state.sizePolicy().hasHeightForWidth())
        self.label_actuator_state.setSizePolicy(sizePolicy)
        self.label_actuator_state.setMinimumSize(QtCore.QSize(0, 50))
        self.label_actuator_state.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_actuator_state.setScaledContents(False)
        self.label_actuator_state.setAlignment(QtCore.Qt.AlignCenter)
        self.label_actuator_state.setWordWrap(False)
        self.label_actuator_state.setObjectName("label_actuator_state")
        self.verticalLayout.addWidget(self.label_actuator_state)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Actuator Control Panel"))
        self.label_actuator_name.setText(_translate("Form", "🔧 Actuator Name"))
        self.label_actuator_state.setText(_translate("Form", "✅ Status: Active"))
