# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'relay_d/acquisition/qt_app/ui/containers/imageWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_video = QVideoWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_video.sizePolicy().hasHeightForWidth())
        self.widget_video.setSizePolicy(sizePolicy)
        self.widget_video.setMinimumSize(QtCore.QSize(400, 300))
        self.widget_video.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_video.setObjectName("widget_video")
        self.verticalLayout.addWidget(self.widget_video)
        self.label_topic_name = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_topic_name.sizePolicy().hasHeightForWidth())
        self.label_topic_name.setSizePolicy(sizePolicy)
        self.label_topic_name.setMinimumSize(QtCore.QSize(0, 50))
        self.label_topic_name.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(88)
        self.label_topic_name.setFont(font)
        self.label_topic_name.setScaledContents(False)
        self.label_topic_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_topic_name.setWordWrap(False)
        self.label_topic_name.setObjectName("label_topic_name")
        self.verticalLayout.addWidget(self.label_topic_name)
        self.statusLayout = QtWidgets.QHBoxLayout()
        self.statusLayout.setSpacing(16)
        self.statusLayout.setObjectName("statusLayout")
        self.label_frame_rate = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_frame_rate.sizePolicy().hasHeightForWidth())
        self.label_frame_rate.setSizePolicy(sizePolicy)
        self.label_frame_rate.setMinimumSize(QtCore.QSize(0, 45))
        self.label_frame_rate.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_frame_rate.setScaledContents(False)
        self.label_frame_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_frame_rate.setWordWrap(False)
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.statusLayout.addWidget(self.label_frame_rate)
        self.label_timestamp = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_timestamp.sizePolicy().hasHeightForWidth())
        self.label_timestamp.setSizePolicy(sizePolicy)
        self.label_timestamp.setMinimumSize(QtCore.QSize(0, 45))
        self.label_timestamp.setMaximumSize(QtCore.QSize(16777215, 45))
        self.label_timestamp.setScaledContents(False)
        self.label_timestamp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timestamp.setWordWrap(False)
        self.label_timestamp.setObjectName("label_timestamp")
        self.statusLayout.addWidget(self.label_timestamp)
        self.verticalLayout.addLayout(self.statusLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Video Stream Monitor"))
        self.label_topic_name.setText(_translate("Form", "Topic Name"))
        self.label_frame_rate.setText(_translate("Form", "📊 Frame Rate: 30 FPS"))
        self.label_timestamp.setText(_translate("Form", "🕒 Timestamp: 12:34:56"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
